replicaCount: 2

image:
  repository: 013958955427.dkr.ecr.us-east-1.amazonaws.com/payment-service
  pullPolicy: IfNotPresent
  tag: "b83fe094ae9db65396a20c59f2b2d79c0b3ce0b6"

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

ingress:
  enabled: true
  className: "alb"
  annotations:
    scheme: "internet-facing"
    targetType: "ip"  # Required for EKS Fargate or advanced routing
  paths:
    - path: /
      pathType: Prefix