replicaCount: 2

image:
  repository: 013958955427.dkr.ecr.us-east-1.amazonaws.com/payment-service
  pullPolicy: IfNotPresent
  tag: "1da5549327c10c71dda3af1671039a063a37b49f"

service:
  type: NodePort
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "alb"
  annotations:
    scheme: "internet-facing"
    targetType: "ip"  # Required for EKS Fargate or advanced routing
  paths:
    - path: /
      pathType: Prefix